[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]

[advisories]
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "GPL-3.0-only",
]
exceptions = []

[licenses.private]
ignore = false

[bans]
multiple-versions = "deny"
wildcards = "deny"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
